import { Patient, ClinicalSummary, MedicalHistory, Doctor, DashboardStats } from '@/types';

export const CURRENT_DOCTOR: Doctor = {
  id: 'DOC-402',
  name: 'Dr. Priya Sharma',
  designation: 'Senior Consultant Physician',
  department: 'Internal Medicine & Triage',
  hospital: 'Apex Multi-Speciality Hospital, New Delhi',
  avatar: 'PS',
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    patient_id: 'P1001',
    name: 'Rajesh Kumar',
    age: 48,
    gender: 'Male',
    language: 'hi',
    phone: '+91 98765 43210',
    uhid: 'APX-2026-0891',
    registration_time: '09:15 AM',
  },
  {
    patient_id: 'P1002',
    name: 'Anita Sharma',
    age: 36,
    gender: 'Female',
    language: 'hi',
    phone: '+91 98123 45678',
    uhid: 'APX-2026-0892',
    registration_time: '09:30 AM',
  },
  {
    patient_id: 'P1003',
    name: 'Rahul Singh',
    age: 52,
    gender: 'Male',
    language: 'en',
    phone: '+91 97654 32109',
    uhid: 'APX-2026-0895',
    registration_time: '09:45 AM',
  },
  {
    patient_id: 'P1004',
    name: 'Priya Verma',
    age: 29,
    gender: 'Female',
    language: 'hi',
    phone: '+91 99887 76655',
    uhid: 'APX-2026-0901',
    registration_time: '10:05 AM',
  },
  {
    patient_id: 'P1005',
    name: 'Amit Gupta',
    age: 61,
    gender: 'Male',
    language: 'en',
    phone: '+91 91234 56780',
    uhid: 'APX-2026-0914',
    registration_time: '10:20 AM',
  },
];

export const INITIAL_SUMMARIES: Record<string, ClinicalSummary> = {
  P1001: {
    patient_id: 'P1001',
    current_complaint: 'Chest pain',
    duration: '3 days',
    severity: '7/10',
    associated_symptoms: [
      'Breathlessness on exertion',
      'Mild diaphoresis (sweating)',
      'Substernal pressure sensation',
    ],
    interview_summary:
      'Patient reports retrosternal chest pain for 3 days with breathlessness, worsened on mild exertion. Pain severity is rated 7/10. No radiation to left jaw or arm noted, but accompanied by mild diaphoresis. Patient has history of hypertension and diabetes.',
    past_history: [
      {
        id: 'c1',
        year: '2021',
        condition: 'Essential Hypertension',
        status: 'Active / Under medication',
        notes: 'Diagnosed during routine health checkup. Well controlled.',
      },
      {
        id: 'c2',
        year: '2023',
        condition: 'Type 2 Diabetes Mellitus',
        status: 'Active / Controlled',
        notes: 'HbA1c ~ 7.1% recorded 3 months ago.',
      },
    ],
    medications: [
      {
        id: 'm1',
        name: 'Amlodipine',
        dosage: '5 mg',
        frequency: 'Once daily (Morning)',
        purpose: 'Blood pressure regulation',
      },
      {
        id: 'm2',
        name: 'Metformin',
        dosage: '500 mg',
        frequency: 'Twice daily (After meals)',
        purpose: 'Glycemic control',
      },
    ],
    allergies: ['No known drug allergies (NKDA)'],
    priority_flags: [
      'Priority review: Chest pain with breathlessness',
      'Cardiovascular risk factor: Pre-existing Hypertension & Diabetes',
    ],
    missing_information: [
      'Previous cardiac stress test / ECG records',
      'Recent fasting lipid profile',
    ],
    status: 'Ready for review',
    priority: 'Priority',
    arrival_time: '09:15 AM',
    timeline: [
      {
        id: 't1',
        date: 'March 2021',
        year: '2021',
        fact: 'Hypertension diagnosed during routine master health checkup',
        source: 'EMR',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't2',
        date: 'July 2023',
        year: '2023',
        fact: 'Type 2 Diabetes diagnosed; commenced on Metformin 500mg BD',
        source: 'Clinical Record',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't3',
        date: 'September 2026 (Today)',
        year: '2026',
        fact: 'Current complaint: Onset of central chest tightness with breathlessness × 3 days',
        source: 'Patient Interview',
        confidence: 'High',
        category: 'complaint',
      },
    ],
    transcript: [
      {
        id: 'msg-1',
        sender: 'ai',
        text: 'नमस्ते राजेश जी। मेदिमार्थी (Medisaarthi) में आपका स्वागत है। आपको किस वजह से आज अस्पताल आना पड़ा?',
        timestamp: '09:18 AM',
      },
      {
        id: 'msg-2',
        sender: 'patient',
        text: 'मुझे तीन दिन से सीने में दर्द हो रहा है और भारीपन लगता है।',
        timestamp: '09:19 AM',
        extracted_info: [
          { label: 'Chief Complaint', value: 'Chest pain' },
          { label: 'Duration', value: '3 days' },
        ],
      },
      {
        id: 'msg-3',
        sender: 'ai',
        text: 'समझ गया। दर्द कितना तीव्र (severe) है? अगर 1 से 10 के पैमाने पर बताएं तो कितना होगा?',
        timestamp: '09:19 AM',
      },
      {
        id: 'msg-4',
        sender: 'patient',
        text: 'लगभग 7 आउट ऑफ 10. चलने पर बढ़ जाता है।',
        timestamp: '09:20 AM',
        extracted_info: [{ label: 'Severity', value: '7/10' }],
      },
      {
        id: 'msg-5',
        sender: 'ai',
        text: 'क्या आपको इसके साथ सांस लेने में दिक्कत या पसीना आ रहा है?',
        timestamp: '09:20 AM',
      },
      {
        id: 'msg-6',
        sender: 'patient',
        text: 'हाँ, सांस लेने में थोड़ी तकलीफ होती है और हल्का पसीना भी आता है।',
        timestamp: '09:21 AM',
        extracted_info: [
          { label: 'Associated Symptoms', value: 'Breathlessness, Diaphoresis' },
        ],
      },
      {
        id: 'msg-7',
        sender: 'ai',
        text: 'क्या आप पहले से किसी बीमारी जैसे बीपी या शुगर की दवा ले रहे हैं?',
        timestamp: '09:21 AM',
      },
      {
        id: 'msg-8',
        sender: 'patient',
        text: 'हाँ, मुझे 2021 से बीपी (Amlodipine 5mg) और 2023 से शुगर (Metformin 500mg) है।',
        timestamp: '09:22 AM',
        extracted_info: [
          { label: 'Past History', value: 'Hypertension (2021), Diabetes (2023)' },
          { label: 'Medications', value: 'Amlodipine 5mg, Metformin 500mg' },
        ],
      },
      {
        id: 'msg-9',
        sender: 'ai',
        text: 'धन्यवाद राजेश जी। आपकी सभी जानकारियां सुरक्षित रूप से संकलित कर ली गई हैं और डॉक्टर शर्मा के लिए तैयार हैं।',
        timestamp: '09:23 AM',
      },
    ],
  },
  P1002: {
    patient_id: 'P1002',
    current_complaint: 'Fever with chills',
    duration: '4 days',
    severity: '6/10',
    associated_symptoms: ['Chills and rigors', 'Generalized body ache', 'Mild dry cough'],
    interview_summary:
      'Patient reports acute high-grade fever for 4 days with intermittent chills and moderate body ache. Peak recorded temperature at home was 101.8°F. Mild dry cough, no breathlessness or sore throat.',
    past_history: [],
    medications: [
      {
        id: 'm-201',
        name: 'Paracetamol',
        dosage: '650 mg',
        frequency: 'SOS for fever > 100°F',
        purpose: 'Antipyretic',
      },
    ],
    allergies: ['Penicillin (causes urticaria / skin hives)'],
    priority_flags: [],
    missing_information: ['Complete Blood Count (CBC) & Dengue NS1 / Malarial Antigen test'],
    status: 'Completed',
    priority: 'Normal',
    arrival_time: '09:30 AM',
    timeline: [
      {
        id: 't-201',
        date: 'September 2026 (4 days ago)',
        year: '2026',
        fact: 'Onset of pyrexia (fever) with chills and muscle fatigue',
        source: 'Patient Interview',
        confidence: 'High',
        category: 'complaint',
      },
    ],
    transcript: [
      {
        id: 'msg-201',
        sender: 'ai',
        text: 'नमस्ते अनीता जी। आपको किस तकलीफ के कारण आना पड़ा?',
        timestamp: '09:32 AM',
      },
      {
        id: 'msg-202',
        sender: 'patient',
        text: 'मुझे 4 दिनों से तेज बुखार और ठंड लग रही है।',
        timestamp: '09:33 AM',
        extracted_info: [
          { label: 'Chief Complaint', value: 'Fever with chills' },
          { label: 'Duration', value: '4 days' },
        ],
      },
    ],
  },
  P1003: {
    patient_id: 'P1003',
    current_complaint: 'Severe throbbing headache',
    duration: '2 days',
    severity: '8/10',
    associated_symptoms: ['Photophobia (light sensitivity)', 'Nausea', 'Visual aura / zig-zag lines'],
    interview_summary:
      'Patient presents with severe unilateral pulsating headache for 48 hours, rated 8/10 severity. Preceded by visual aura. Associated with nausea and photophobia. Relieved partially by quiet dark room.',
    past_history: [
      {
        id: 'c-301',
        year: '2018',
        condition: 'Chronic Migraine with Aura',
        status: 'Recurrent episodes',
        notes: 'Triggered by stress and irregular sleep.',
      },
    ],
    medications: [
      {
        id: 'm-301',
        name: 'Sumatriptan',
        dosage: '50 mg',
        frequency: 'At onset of migraine attack',
        purpose: 'Acute migraine abortive',
      },
      {
        id: 'm-302',
        name: 'Naproxen',
        dosage: '250 mg',
        frequency: 'PRN',
        purpose: 'Analgesic',
      },
    ],
    allergies: ['No known drug allergies (NKDA)'],
    priority_flags: ['Priority review: Acute severe headache with photophobia'],
    missing_information: ['Response to latest sumatriptan dose'],
    status: 'Ready for review',
    priority: 'Priority',
    arrival_time: '09:45 AM',
    timeline: [
      {
        id: 't-301',
        date: 'June 2018',
        year: '2018',
        fact: 'Migraine with visual aura diagnosed by neurologist',
        source: 'EMR',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't-302',
        date: 'September 2026 (Today)',
        year: '2026',
        fact: 'Acute severe exacerbation of unilateral throbbing headache × 2 days',
        source: 'Patient Interview',
        confidence: 'High',
        category: 'complaint',
      },
    ],
    transcript: [
      {
        id: 'msg-301',
        sender: 'ai',
        text: 'Hello Mr. Rahul Singh. What brings you to the hospital today?',
        timestamp: '09:47 AM',
      },
      {
        id: 'msg-302',
        sender: 'patient',
        text: 'I have had a severe throbbing headache for the past two days with light sensitivity.',
        timestamp: '09:48 AM',
        extracted_info: [
          { label: 'Chief Complaint', value: 'Severe throbbing headache' },
          { label: 'Duration', value: '2 days' },
        ],
      },
    ],
  },
  P1004: {
    patient_id: 'P1004',
    current_complaint: 'Acute Lower Right Abdominal Pain',
    duration: '24 hours',
    severity: '8/10',
    associated_symptoms: ['Nausea & anorexia', 'Low grade fever (99.8°F)', 'Pain worsening on movement'],
    interview_summary:
      'Patient reports acute onset periumbilical pain shifting to the Right Iliac Fossa over the past 24 hours. Severity 8/10. Accompanied by nausea, loss of appetite, and mild fever. Needs urgent surgical/clinical evaluation.',
    past_history: [
      {
        id: 'c-401',
        year: '2022',
        condition: 'Hypothyroidism',
        status: 'Stable / Treated',
        notes: 'Euthyroid on current replacement therapy.',
      },
    ],
    medications: [
      {
        id: 'm-401',
        name: 'Levothyroxine',
        dosage: '50 mcg',
        frequency: 'Daily (Empty stomach morning)',
        purpose: 'Thyroid hormone replacement',
      },
    ],
    allergies: ['Sulfa drugs (causes cutaneous maculopapular rash)'],
    priority_flags: [
      'Priority review: Acute Right Lower Quadrant abdominal pain with migration',
      'Requires urgent clinical palpation / surgical exclusion of appendicitis',
    ],
    missing_information: ['Last menstrual period date', 'Abdominal ultrasound report'],
    status: 'Ready for review',
    priority: 'Urgent',
    arrival_time: '10:05 AM',
    timeline: [
      {
        id: 't-401',
        date: 'November 2022',
        year: '2022',
        fact: 'Primary hypothyroidism diagnosed; started on Levothyroxine',
        source: 'Clinical Record',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't-402',
        date: 'September 2026 (Today)',
        year: '2026',
        fact: 'Acute right lower quadrant abdominal pain onset 24h ago',
        source: 'Patient Interview',
        confidence: 'High',
        category: 'complaint',
      },
    ],
    transcript: [
      {
        id: 'msg-401',
        sender: 'ai',
        text: 'नमस्ते प्रिया जी। आपको किस तकलीफ की वजह से परामर्श की आवश्यकता है?',
        timestamp: '10:07 AM',
      },
      {
        id: 'msg-402',
        sender: 'patient',
        text: 'कल रात से पेट के निचले दाहिने हिस्से में बहुत तेज दर्द हो रहा है और उल्टी जैसा लग रहा है।',
        timestamp: '10:08 AM',
        extracted_info: [
          { label: 'Chief Complaint', value: 'Right Lower Abdominal Pain' },
          { label: 'Duration', value: '24 hours' },
          { label: 'Severity', value: '8/10' },
        ],
      },
    ],
  },
  P1005: {
    patient_id: 'P1005',
    current_complaint: 'Chronic Lower Back Pain exacerbation',
    duration: '2 weeks',
    severity: '6/10',
    associated_symptoms: ['Radiation to left posterior thigh', 'Stiffness after prolonged sitting'],
    interview_summary:
      'Patient reports 2-week worsening of longstanding lower lumbar back pain. Radiates down left posterior thigh to knee. No urinary or bowel incontinence. History of lumbar spondylosis.',
    past_history: [
      {
        id: 'c-501',
        year: '2019',
        condition: 'Lumbar Spondylosis (L4-L5)',
        status: 'Chronic intermittent',
        notes: 'MRI in 2019 showed mild disc bulge.',
      },
      {
        id: 'c-502',
        year: '2020',
        condition: 'Dyslipidemia',
        status: 'Controlled on statin',
        notes: 'Lipids within target range.',
      },
    ],
    medications: [
      {
        id: 'm-501',
        name: 'Atorvastatin',
        dosage: '20 mg',
        frequency: 'Nightly',
        purpose: 'Cholesterol lowering',
      },
      {
        id: 'm-502',
        name: 'Aceclofenac',
        dosage: '100 mg',
        frequency: 'PRN after meals',
        purpose: 'NSAID / Analgesic',
      },
    ],
    allergies: ['No known drug allergies (NKDA)'],
    priority_flags: [],
    missing_information: ['Recent lumbar spine X-ray / Physiotherapy compliance'],
    status: 'Verified',
    priority: 'Normal',
    arrival_time: '10:20 AM',
    verified_by: 'Dr. Priya Sharma',
    verified_at: '10:45 AM',
    timeline: [
      {
        id: 't-501',
        date: 'January 2019',
        year: '2019',
        fact: 'Lumbar spondylosis diagnosed on MRI lumbar spine',
        source: 'EMR',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't-502',
        date: 'August 2020',
        year: '2020',
        fact: 'Dyslipidemia diagnosed; started on Atorvastatin 20mg',
        source: 'Clinical Record',
        confidence: 'High',
        category: 'condition',
      },
      {
        id: 't-503',
        date: 'September 2026 (Today)',
        year: '2026',
        fact: '2-week flare of mechanical lower back pain radiating to left leg',
        source: 'Patient Interview',
        confidence: 'High',
        category: 'complaint',
      },
    ],
    transcript: [
      {
        id: 'msg-501',
        sender: 'ai',
        text: 'Hello Mr. Amit Gupta. What symptoms would you like the doctor to review today?',
        timestamp: '10:22 AM',
      },
      {
        id: 'msg-502',
        sender: 'patient',
        text: 'My lower back pain has flared up over the last two weeks and shoots down my left leg.',
        timestamp: '10:23 AM',
        extracted_info: [
          { label: 'Chief Complaint', value: 'Lower back pain flare' },
          { label: 'Duration', value: '2 weeks' },
        ],
      },
    ],
  },
};
